### ISSUE TITLE
Slight improvements

### ISSUE THREAD

**Issue by BananaPuncher714** [PikaMug/LocaleLib#1]
On line [57](https://gist.github.com/PikaMug/eeb622a5c609bd00d1db3de4794b3424#file-localequery-class-L57), I would suggest checking if `Material.getMaterial("LINGERING_POTION")` returns `null` as opposed to looping through all the materials.

I would also suggest making your key maps `final` and your methods to create keys return immutable maps instead of making a new map each time.

Lastly, your use of a switch statement on line [282](https://gist.github.com/PikaMug/eeb622a5c609bd00d1db3de4794b3424#file-localequery-class-L282) can be simplified by removing the `return true;` after each case except for the last one like so:
```java
switch(bukkitVersion) {
case "1.12.2" :
case "1.12.1" :
case "1.12" :
...
case "1.7.2" :
    return true;
default:
    return false;
}
```

**Comment by PikaMug** [comment]
Thanks for the suggestions!

Great catch on the loop and switch statement. Done!

I assume you were looking at [the Gist](https://gist.github.com/PikaMug/eeb622a5c609bd00d1db3de4794b3424/cf50749ca6dc4b7db11b2342a9440d04120cf17b) in which I mistakenly made some create keys methods private when it was my intention they be public. My thoughts were that someone may wish to obtain the map and use/modify it for whatever purpose. For that reason, I feel it is not desirable to return an ImmutableMap (although I know it maintains insertion order just like LinkedHashMap).
