### ISSUE TITLE
Version 1.6 isn't available.

### ISSUE THREAD

**Issue by Sven65** [PikaMug/LocaleLib#10]
Going to [the maven repo](https://jitpack.io/com/github/PikaMug/LocaleLib/) for the plugin, we have three versions, 1.0, 1.1 and `af35481`, but not 1.6, as the documentation says.

Just thought I'd let you know so it can be sorted out :)

**Comment by PikaMug** [comment]
Thanks, this is because I've been neglecting to publish releases at https://github.com/PikaMug/LocaleLib/releases

Please check again.

**Comment by Sven65** [comment]
Still says it's not available. Might take some time though?

**Comment by Sven65** [comment]
Yup! There we go, thanks!
