### ISSUE TITLE
No keys for 1.16 items and blocks?

### ISSUE THREAD

**Issue by Sven65** [PikaMug/LocaleLib#11]
Looking through the code out of interest, I noticed that LocaleKeys.java doesn't contain any keys for the new 1.16 items such as netherrite, lanterns and more new items from 1.16, is this intentional or just an oversight somehere?

**Comment by PikaMug** [comment]
This is intentional - keys are for items from Minecraft 1.12 and below. Anything 1.13+ is fetched using modern methods.
