### ISSUE TITLE
I don't know how to install it...

### ISSUE THREAD

**Issue by oski32166** [PikaMug/LocaleLib#12]
Quests and ChestShop still show item name in english altough menu is in right language. Just placing jar in plugin folder isn't working.

**Comment by PikaMug** [comment]
Item names are translated into the _client's_ language, meaning you need to change your Minecraft game settings.

The current version of Quests includes this functionality built-in; you do not need to "install" this resource. Furthermore, ChestShop does not currently utilize LocaleLib as far as I can tell, so you won't see any difference there.

**Comment by oski32166** [comment]
If Quests includes it then it's weird... My game settings are changed to polish language, locale in essentialsx is even in pl. I don't know what to do anymore. It's not big problem for me, but bigger for my friends who can't speak english. Anyway, thanks for your reply and your amazing work on plugins.
![2021-01-08_04 42 36](https://user-images.githubusercontent.com/77134938/103972023-60f63c80-516c-11eb-868d-ea00c988e8a4.png)

**Comment by oski32166** [comment]
> Item names are translated into the _client's_ language, meaning you need to change your Minecraft game settings.
> 
> The current version of Quests includes this functionality built-in; you do not need to "install" this resource. Furthermore, ChestShop does not currently utilize LocaleLib as far as I can tell, so you won't see any difference there.

Oh, and also when using /give command message appear in polish but with item name in english.

**Comment by PikaMug** [comment]
@oski32166 It looks like only item rewards are not being translated. If you would [create an issue on the Quests repository](https://github.com/PikaMug/Quests) I would be glad to look into this futher.
