### ISSUE TITLE
Lapis Ore and Lapis Block names are swaped

### ISSUE THREAD

**Issue by LeovecCZ** [PikaMug/LocaleLib#16]
https://github.com/PikaMug/LocaleLib/blob/398781f85e715230edb2965ae310890b4c99981a/src/main/java/me/pikamug/localelib/LocaleKeys.java#L278-L279
I think these lines should be:
`keys.put("LAPIS_BLOCK", "tile.blockLapis.name");`
`keys.put("LAPIS_ORE", "tile.oreLapis.name");`

**Comment by PikaMug** [comment]
Looks like you're right. Thanks!
