### ISSUE TITLE
Lib references the Quests plugin in error message

### ISSUE THREAD

**Issue by MaowImpl** [PikaMug/LocaleLib#19]
I assume this was left over from transitioning LocaleLib over from Quests or something, but it can be confusing (if the message ever gets sent, that is)

https://github.com/PikaMug/LocaleLib/blob/9343e310d5fc2ee9c74d1a272e73dafab8418b3d/src/main/java/me/pikamug/localelib/LocaleManager.java#L472

**Comment by PikaMug** [comment]
Correct, thank you for catching that.
