### ISSUE TITLE
Documentation does not show proper access to LocaleManager

### ISSUE THREAD

**Issue by i509VCB** [PikaMug/LocaleLib#2]
In the documentation on spigot there is this line of code to show how to grab the LocaleManager (Version 1.2):
```
private LocaleManager localeManager;
@Override
public void onEnable() {
   localeManager = LocaleLib.getLocaleManager();
}
```

However this does not work as getLocaleManager is not statically accessible. 

Either you need to make getLocaleManager work statically or change your documentation to this:

```
public void onEnable() {
    LocaleLib localeLib = (LocaleLib) getServer().getPluginManager().getPlugin("LocaleLib");
    manager = localeLib.getLocaleManager();
}
```

Though for sake of keeping the current documentation minimally changed, making getLocaleManager static would be the best option.

**Comment by PikaMug** [comment]
Whoops, thanks for pointing that out! I've updated the Spigot page.
