### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by YrChen1001** [PikaMug/LocaleLib#21]
[13:58:20 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

**Comment by PikaMug** [comment]
This is a mandatory Bukkit error created when supporting item materials for pre-1.13 versions. It can be ignored.

**Comment by YrChen1001** [comment]
However, the project name is not automatically translated, but it is not displayed
I'm using on 1.18.2 paper server

**Comment by PikaMug** [comment]
Feel free to create a new issue with more information, then. The error you shared here is unrelated.
