### ISSUE TITLE
wrong blockmapping

### ISSUE THREAD

**Issue by PublicGameCoder** [PikaMug/LocaleLib#8]
https://github.com/PikaMug/LocaleLib/blob/6090bb034fb6cb9b75b07d77a15955b886c14a86/src/main/java/me/pikamug/localelib/LocaleKeys.java#L329

``REDSTONE_ORE`` should be ``REDSTONE_BLOCK``

**Comment by PublicGameCoder** [comment]
https://github.com/PikaMug/LocaleLib/blob/6090bb034fb6cb9b75b07d77a15955b886c14a86/src/main/java/me/pikamug/localelib/LocaleKeys.java#L454

``REDSTONE_COMPARATOR_OFF`` should be ``REDSTONE_COMPARATOR_ON``

**Comment by PublicGameCoder** [comment]
Some (music disc) nameKeys are different between minecraft versions.
You can check the right values inside each version's jar by opening it with something like Winrar, then go to assets/minecraft/lang/ and the en_us.json should be located there.

**Comment by PikaMug** [comment]
Fixed in fc8f9437713e1704714eb5b5c4a74250555d8545
